---
- hosts: webservers
  become: true
  remote_user: user
  vars:
    temp_path: /tmp
  roles:
  - httpd

- hosts: eap
  become: true
  remote_user: user
  vars:
    temp_path: /tmp
  roles:
  - eap
  
- hosts: eap-domains
  become: true
  remote_user: user
  vars:
    temp_path: /tmp
  roles:
  - eap-domain
  
- hosts: eap-nodes
  become: true
  remote_user: user
  vars:
    temp_path: /tmp
  roles:
  - eap-node
  
