---
- hosts: eap
  become: true
  remote_user: user
  vars:
    temp_path: /tmp
    jboss_home: /opt/jboss/jboss-eap-7.0
    httpd_home: //
  roles:
  - eap
  
- hosts: eap-domains
  become: true
  remote_user: user
  vars:
    temp_path: /tmp
    jboss_home: /opt/jboss/jboss-eap-7.0
    httpd_home: //
  roles:
  - eap-domain
  
- hosts: eap-nodes
  become: true
  remote_user: user
  vars:
    temp_path: /tmp
    jboss_home: /opt/jboss/jboss-eap-7.0
    httpd_home: //
  roles:
  - eap-node